<?php return array (
  'About Files' => 'À propos des fichiers',
  'Upload Files, File Revisions and Collaborate' => 'Envoi de fichiers, révisions de fichiers et collaborer ',
  'Use Files section to upload files, discuss them, upload and compare versions and more. You can upload and track versions of any file. Files attached to objects in other sections of project are also listed here' => 'Utiliser la rubrique des fichiers pour envoyer des documents, en discuter, envoyer et comparer différente version et bien plus. Vous pouvez envoyer et archiver n\'importe quel type de fichier. Les fichiers attachés à des objets dans les autres rubriques d\'un projet sont listés ici.',
  'Organize in Categories and Associate with Milestones' => 'Organiser dans les catégories et associer à des jalons',
  'Files can be sorted in categories and associated with milestones; both relations are optional. Filter files by category using the tabs on the right' => 'Les fichiers peuvent être classés dans des catégories et assignés à des jalons. Ces relations sont optionnelles. Il est possible de filtrer les fichiers par catégories en utilisant les onglets à votre droite',
  'Have a Discussion with your Team or Clients' => 'Ayez une discussion avec votre équipe et vos clients',
  'Post an unlimited number of comments. Use them to discuss file and file revisions with your colleagues and clients' => 'Partager un nombre illimité de commentaires. Utilisez-les pour discuter d\'un fichier et des révisions avec vos collègues et clients',
  'Subscribe to a file to receive email notification when new revision is uploaded or new comment is posted. The Person who uploaded the file can edit the list of subscribers using Manage Subscriptions tool (available from Options menu)' => 'S’abonner à un fichier permet de recevoir des notifications e-mail quand une nouvelle révision est envoyée ou un nouveau commentaire est publié. La personne qui a envoyé le fichier peut éditer la liste des abonnés en utilisant l’outil de gestion des abonnements (disponible depuis le menu de réglages)',
  'Older Versions' => 'Versions plus anciennes',
  'Delete Permanently' => 'Supprimer définitivement',
  'Page :page' => 'Page :page',
  'Thumbnail' => 'Miniature',
  'File Details' => 'Détails du fichier',
  'File' => 'Fichier',
  'Attached To' => 'Attaché à',
  'Download' => 'Télécharger',
  'There are no files in this category' => 'Il n\'y a aucun fichier dans cette catégorie',
  'Upload now' => 'Envoyer un fichier maintenant',
  'There are no files to show' => 'Il n\'y a aucun fichier à afficher',
  'All Files' => 'Tous les fichiers',
  'All Attachments' => 'Tous les attachements',
  'Manage Categories' => 'Gérer les catégories',
  'Edit File Details' => 'Modifier les détails du fichier',
  'Category' => 'Catégories',
  'Files' => 'Fichiers',
  'There are no files on this page' => 'Il n\'y a aucun fichier sur cette page',
  'Latest Version' => 'Dernière version',
  'This has no revisions' => 'Ceci n\'a pas de révision',
  'First Version' => 'Première version',
  'New Version' => 'Nouvelle version',
  'Move To Trash' => 'Déplacer vers la corbeille',
  'Move To Category' => 'Déplacer vers la catégorie',
  '&lt;None&gt;' => '&lt;Aucun&gt;',
  'Select File' => 'Sélectionner le fichier',
  'You are about to upload new version of <a href=":url">":name"</a> file. Older versions of this file will not be deleted but saved for future reference' => 'Vous êtes en train d\'envoyer une nouvelle version du fichier <a href=":url">":name"</a>. Les anciennes versions du fichier ne seront pas effacées, mais sauvegardées pour une utilisation future',
  'Notify People' => 'Alerter les collaborateurs',
  'File <a href=":url">:name</a> has been created' => 'Le fichier <a href=":url">:name</a> a été créé',
  'Set Milestone and Category' => 'Définir le jalon et la catégorie',
  'Set Category' => 'Définir la catégorie',
  'Set Visibility' => 'Définir la visibilité',
  'Upload Files' => 'Envoyer des fichiers',
  'Description <i>(optional)</i>' => 'Description <i>(optionnel)</i>',
  'Add Another File' => 'Ajouter un autre fichier',
  '<strong>Note</strong>: Max upload size is :max_size per file' => '<strong>Remarque</strong>: la taille maximale des envois de fichiers est :max_size per file',
  'Upload' => 'Envoyer',
  'File Name' => 'Nom du fichier',
  'Image preview. <a href=":url">Click to download</a> full size image' => 'Image d\'aperçu. <a href=":url">Cliquer pour télécharger</a> l\'image en taille réelle',
  'Description for this file is not provided' => 'La description pour ce fichier n\'a pas été fournie',
  'Invalid file - last revision was not found' => 'Fichier invalide - La dernière révision n\'a pas été trouvée.',
  'Please select what you want to do with selected tickets' => 'Merci de sélectionner ce que vous voulez faire avec des billets sélectionnés',
  'Please select files that you would like to update' => 'Merci de sélectionner les fichiers que vous souhaitez mettre à jour',
  'File ":name" has been updated' => 'Le fichier ":name" a été mis à jour',
  'File not uploaded' => 'Fichier non envoyé',
  ':count attachments deleted' => ':count attachements supprimés',
  ':count files moved to trash' => ':count fichiers déplacés à la corbeille',
  ':count files updated' => ':count fichiers mis à jour',
  'You haven\'t selected any file for upload' => 'Vous n\'avez sélectionné aucun fichier à envoyer',
  'Adds file repository to each project. Highlights: files support versioning, can have comments, email notifications, can be organized in categories and more...' => 'Ajouter des fichiers au référentiel de chaque projet. Points forts: gestionnaire de versions des fichiers , ils peuvent avoir des commentaires, des notifications par courrier électronique, ils peuvent être organisés en catégories et bien plus',
  'Module will be deactivated. All files created with this module will be deleted. Files attached to objects in other modules (tickets, comments etc) will not be deleted' => 'Ce module sera désactivé. Tous les fichiers créés avec ce module seront supprimés. Les fichiers attachés aux objets dans d\'autres modules (tickets, commentaires, etc.) ne seront pas supprimés',
  'File categories' => 'Catégories du fichier',
  'Exporting files data...' => 'Exportation des données des fichiers',
  '<a href=":user_url">:user_name</a> uploaded a new file' => '<a href=":user_url">:user_name</a> a envoyé un nouveau fichier',
  '<a href=":user_url">:user_name</a> uploaded a new file to <a href=":project_view_url">:project_name</a> project' => '<a href=":user_url">:user_name</a> a envoyé un nouveau fichier dans le projet <a href=":project_view_url">:project_name</a>',
  '<a href=":user_url">:user_name</a> uploaded a new version of <a href=":url">:name</a> file' => '<a href=":user_url">:user_name</a> a envoyé une nouvelle version du fichier <a href=":url">:name</a>',
  '<a href=":user_url">:user_name</a> uploaded a new version of <a href=":url">:name</a> file in <a href=":project_view_url">:project_name</a> project' => '<a href=":user_url">:user_name</a> a envoyé une nouvelle version du fichier <a href=":url">:name</a> dans le projet <a href=":project_view_url">:project_name</a>',
  'File name is required' => 'Le nom du fichier est obligatoire',
  'All revision moved to Trash' => 'Toutes les révisions ont été déplacées ves la corbeille',
  'Upload <a href=":upload_url">more files</a> or go back to <a href=":files_url">Files</a> section' => 'Envoyer <a href=":upload_url">plus de fichiers</a> ou retourner en arrière à la section <a href=":files_url">Fichiers</a>',
  'Uploading files' => 'Fichiers en cours d\'envoi',
  'Done, :files_uploaded files uploaded and :files_failed uploads failed<br />' => 'Terminé, :files_uploaded fichiers ont été envoyés et :files_failed envois ont échoué<br />',
  'Done, :files_uploaded files uploaded<br />' => 'Terminé, :files_uploaded fichiers ont été envoyés<br />',
  'Done, :files_failed uploads failed<br />' => 'Terminé, :files_failed envois ont échoué<br />',
) ?>