<?php return array (
  'Notify People' => 'Alerter les personnes',
  'Category' => 'Catégorie',
  'Add discussion' => 'Ajouter une discussion',
  'New Discussion' => 'Nouvelle discussion',
  'Update Discussion' => 'Mettre à jour la discussion',
  'Discussions' => 'Discussions',
  'There are no discussions on this page' => 'Il n\'y a aucune discussion sur cette page',
  'Discussion' => 'Discussion',
  'Replies' => 'Réponses',
  'Last Reply' => 'Dernière réponse',
  'by <a href=":user_url">:user_name</a>' => 'par <a href=":user_url">:user_name</a>',
  'No discussions in this category' => 'Aucune discussion dans cette catégorie',
  'Start one now' => 'Commencer une discussion maintenant !',
  'No discussions here' => 'Il n\'y a aucune discussion içi',
  'All Discussions' => 'Toutes les discussions',
  'Manage Categories' => 'Gérer les catégories',
  'Discussion <a href=":url">:name</a> has been created' => 'La discussion <a href=":url">:name</a> a été créée',
  'Set Milestone and Category' => 'Définir le jalon et la catégorie',
  'Set Category' => 'Définir la catégorie',
  'Set Visibility' => 'Définir la visibilité',
  'Page :page' => 'Page :page',
  'About Discussions' => 'À propos des discussions',
  'Just Like Online Forums' => 'Comme un forum de discussions',
  'Discussions let you create a number of topics and discuss them with your team and clients. It works just like online forums - system will tell you when there are new messages in a topic and discussions with most recent comments are listed on top' => 'Les discussions permettent de créer un nombre illimité de sujets afin de discuter avec votre équipe et vos clients. Cela fonctionne de la même façon qu\'un forum de discussions conventionnel, le système vous alertera lorsqu\'il y a de nouveaux messages dans un sujet. Enfin, les discussions avec les commentaires les plus récents sont affichées en premier.',
  'Organize in Categories and Associate with Milestones' => 'Organisé dans des catégories et associé à des jalons',
  'Discussions can be sorted in categories and associated with milestones; both relations are optional. Filter discussions by category using the tabs on the right' => 'Les discussions peuvent être classées dans des catégories et associées à des jalons, ces relations sont optionnelles. Vous pouvez filtrer les discussions par catégories en utilisant l\'onglet à votre droite.',
  'Attach Unlimited Number of Files' => 'Attacher un nombre illimité de fichiers',
  'Every discussion message can have an unlimited number of attachments. System will use icons for various file types and thumbnails for images' => 'Chaque message de la discussion peut avoir un nombre illimité de pièces jointes. Le système affichera des icônes pour chaque type de fichiers et des miniatures pour les images.',
  'Subscribe to a discussion to receive an email notification when new message is posted. Discussion subscribers can be managed using Manage Subscriptions tool (available from Options menu)' => 'S\'(abonner à une discussion permet de recevoir une alerte e-mail lorsqu\'un nouveau message est publié. Les abonnés à la discussion peuvent être gérés en utilisant le gestionnaire d\'abonnements (disponible depuis le menu options)',
  'Failed to pin selected discussion' => 'Impossible d\'épingler la discussion sélectionnée',
  'Failed to unpin selected discussion' => 'Impossible de détacher la discussion sélectionnée',
  'Discussion :discussion_name has been started' => 'La discussion :discussion_name vient d\'être lancée',
  'Discussion ":name" has been updated' => 'La discussion :discussion_name a été mise à jour',
  'Discussion has been successfully pinned' => 'La discussion a été épinglée avec succès',
  'Discussion has been successfully unpinned' => 'La discussion a été détachée avec succès',
  '<strong>Pinned</strong> - This discussion is pinned' => '<strong>Eplinglé</strong> - Cette discussion est épinglée',
  'Adds discussion boards to projects' => 'Ajouter les forums de discussion aux projets',
  'Module will be deactivated. All discussions from all projects will be deleted' => 'Ce module sera désactivé. Toutes les discussions de tous les projets seront effacées',
  'Discussion categories' => 'Catégories de la discussion',
  'Toggle Details' => 'Afficher/masquer les détails',
  'Exporting discussions data...' => 'Exportation des données des discussions',
  'Pin' => 'Marquer',
  '<a href=":user_url">:user_name</a> pinned <a href=":url">:name</a> discussion' => '<a href=":user_url">:user_name</a> a marqué la discussion <a href=":url">:name</a>',
  '<a href=":user_url">:user_name</a> pinned <a href=":url">:name</a> discussion in <a href=":project_view_url">:project_name</a> project' => '<a href=":user_url">:user_name</a> a marqué la discussion <a href=":url">:name</a> dans le projet <a href=":project_view_url">:project_name</a>',
  ':user_name pinned <a href=":object_url">:object_name</a> discussion' => ':user_name a marqué la discussion <a href=":object_url">:object_name</a',
  '<a href=":user_url">:user_name</a> unpinned <a href=":url">:name</a> discussion' => '<a href=":user_url">:user_name</a> a démarqué la discussion <a href=":url">:name</a>',
  '<a href=":user_url">:user_name</a> unpinned <a href=":url">:name</a> discussion in <a href=":project_view_url">:project_name</a> project' => '<a href=":user_url">:user_name</a> a démarqué la discussion <a href=":url">:name</a> dans le projet <a href=":project_view_url">:project_name</a>',
  ':user_name unpinned <a href=":object_url">:object_name</a> discussion' => ':user_name a démarqué la discussion <a href=":object_url">:object_name</a',
  'Summary is required (min 3 letters)' => 'Le résumé est obligatoire (minimum 3 lettres)',
  'Message is required (min 3 letters)' => 'Le message est obligatoire (minimum 3 lettres)',
) ?>