<?php return array (
  'Backup Settings' => 'Réglages de la sauvegarde',
  'How many backups to keep:' => 'Combien de sauvegarde souhaitez-vous conserver :',
  'Enable backup:' => 'Activer la sauvegarde :',
  'Automatic backup is <strong>enabled</strong>' => 'La sauvegarde automatique est <strong>activée</strong>',
  'Your next backup will be approximately <strong>:size</strong> in size' => 'La prochaine sauvegarde fera approximativement en taille <strong>:size</strong>',
  'Automatic backup is <strong>disabled</strong>' => 'La sauvegarde automatique est <strong>désactivée</strong>',
  ':number_of_backups last backups will be kept' => 'Les :number_of_backups dernières sauvegardes seront conservées',
  'All backups will be kept' => 'Toutes les sauvegardes seront conservées',
  'Existing backups' => 'Sauvegardes existantes',
  'Backup Date' => 'Date de la sauvegarde',
  'Backup Size' => 'Poids de la sauvegarde',
  'Backup State' => 'État de la sauvegarde',
  'Valid' => 'Valide',
  'Backup folder size: <strong>:size</strong>' => 'La taille du dossier des sauvegardes : <strong>:size</strong>',
  'Backup' => 'Sauvegarder',
  'Automatically create daily backup of your activeCollab data' => 'Créer automatiquement une sauvegarde journalière de vos données activeCollab',
  'Module will be deactivated. Backups created with this module will not be deleted.' => 'Le module sera désactivé. Les sauvegardes créées avec ce module ne seront pas effacées.',
  'Backup settings have been updated' => 'Les réglages de sauvegardes ont été mis à jour',
  'Automatic backup of your activeCollab installation' => 'Sauvegarde automatique de votre installation activeCollab',
  'Backup is Corrupted' => 'La sauvegarde est corrompue',
  'Backup is Corrupted. Database backup is missing' => 'La sauvegarde est corrompue. Les paramètres de base de données sont manquants.',
  '<strong>:filesize</strong> is file size of database backup' => '<strong>:filesize</strong> est la taille de la base de données sauvegardée',
  '<strong>:count</strong> uploaded files backed up' => '<strong>:count</strong> fichiers envoyés sauvegardés',
  '<strong>:count</strong> avatars backed up' => '<strong>:count</strong> avatars sauvegardés',
  '<strong>:count</strong> projects icons backed up' => '<strong>:count</strong> icônes de projets sauvegardés',
  '<strong>:count</strong> customer logos backed up' => '<strong>:count</strong> logos de clients sauvegardés',
) ?>