<?php return array (
  'Full description' => 'Description complète',
  'New Checklist' => 'Nouvelle liste de tâches',
  'Completed Checklists' => 'Liste de tâches complétées',
  ':open open tasks of :total tasks in the list' => ':open tâches ouvertes sur :total tâches dans la liste',
  'There are no active checklists here' => 'Il n\'y a aucune liste de tâches active ici',
  'Edit checklist' => 'Modifier la liste de tâches',
  'Checklists' => 'Liste de tâches',
  'Active Checklist' => 'Liste de tâches active',
  'There are no active checklists in this project' => 'Il n\'y a aucune liste de tâches active dans ce projet',
  'Completed Checklist' => 'Liste de tâches terminée',
  'Checklist' => 'Liste de tâches',
  'Active Checklists' => 'Listes de tâches active',
  ':open_count open tasks of :total_count tasks in list' => ':open_count tâches ouvertes sur :total_count tâches dans la liste',
  'Assignees for Tasks' => 'Responsables des tâches',
  'Checklists <a href=":url">:name</a> has been created' => 'La liste de tâches :name a été créée',
  'Set Milestone' => 'Fixer le jalon',
  'Set Visibility' => 'Fixer la catégorie',
  'Open' => 'Ouvert',
  'Description for this checklist is not provided' => 'La description pour cette liste de tâches n\'a pas été fournie',
  'About Checklists' => 'À propos de la liste de tâches',
  'Lists of Tasks' => 'Listes de tâches',
  'Checklist is a list of tasks that need to be done in order to get a checklist completed. When all tasks in the checklist are completed, the checklist is completed automatically. Every task in a list can have priority, due date and multiple assignees' => 'La liste de tâches est composée, elles doivent être faites afin d\'obtenir une liste de tâches terminée. Lorsque toutes les tâches sont terminées, la liste de tâches est automatiquement complétée. Chaque tâche dans une liste peut avoir une priorité, une date d\'échéance et plusieurs responsables',
  'Subscribe to checklist tasks to receive email notification when tasks are completed or reopened' => 'Abonnez-vous à liste de tâches pour recevoir un courriel lorsque les tâches sont accomplies ou rouvertes',
  'Adds simple task lists to projects' => 'Ajoute une liste de tâches simples aux projets ',
  'Module will be deactivated and all checklists from all projects will be deleted' => 'Le module sera désactivé et toutes les listes de tâches de tous les projets seront supprimées',
  'Checklist :name has been added' => 'La liste de tâches :name a été ajoutée',
  'Checklist :name has been updated' => 'La liste de tâches :name a été mise à jour',
  'Exporting checklists data...' => 'Exportation des données des listes de tâches...',
  'Checklist summary is required' => 'Le résumé de la liste de tâches est obligatoire',
) ?>