<?php return array (
  'Submit Ticket / :company' => 'Envoyer le ticket / :company',
  'Submit Ticket' => 'Envoyer le ticket',
  'Your Email Address' => 'Votre adresse courriel',
  'Your Name' => 'Votre nom',
  'Category' => 'Catégorie',
  'Full Description' => 'Description complète',
  'Type the code shown' => 'Le type de code affiché',
  'Public Submit Settings' => 'Réglages de l\'ajout de public de tickets',
  'Project for tickets:' => 'Projet pour les tickets :',
  'Enable captcha:' => 'Activer le captcha :',
  'Enable public submit:' => 'Activer l\'ajout de public de tickets :',
  'When enabled, Public Submit module will let people submit tickets through a form on your website without having to be a registered and logged in the system. This module is great for receiving support requests or getting feedback from users' => 'Lorsqu\'il est activé, le module d\'ajout public de tickets permettra aux gens de soumettre des billets par l\'intermédiaire d\'un formulaire sur votre site web sans avoir à être inscrits et connectés au système. Ce module est super pour recevoir les demandes de supports et les retours d\'expériences des utilisateurs',
  'Public Submit is <strong>enabled</strong>' => 'L\'ajout public de tickets est <strong>activé</strong>',
  'Submission form is located here: <a href=":url" target="_blank">:url</a>' => 'Le formulaire d\'ajout est situé ici : <a href=":url" target="_blank">:url</a>',
  'After user submits data, a new ticket is created in <a href=":url">:project_name</a> project.' => 'Après qu\'un utilisateur ait envoyé ses données, un nouveau ticket est créé dans le projet <a href=":url">:project_name</a>.',
  'You need to specify default project for newly created tickets first.' => 'Vous devez spécifier un projet par défaut avant de créer un nouveau ticket.',
  'GD Library with FreeType2 is required for captcha protection. <a href=":gd_url">Read more about GD Library</a>' => 'La librairie GD avec FreeType2 est obligatoire pour la protection captcha. <a href=":gd_url">En savoir plus sur la librairie GD</a>',
  'Public Submit is <strong>disabled</strong>' => 'L\'ajout public de tickets est <strong>désactivé</strong>',
  'GD Library is required for captcha protection. <a href=":gd_url">Read more about GD Library</a>' => 'La librairie GD est obligatoire pour la protection captcha. <a href=":gd_url">En savoir plus sur la librairie GD</a>',
  'Public Submit' => 'Ajout public de tickets',
  'Public Submit settings have been updated' => 'Les réglages d\'ajout public de tickets ont été mis à jour',
  'Code you entered is not valid' => 'Le code saisi est invalide',
  'Information about Public Submit module' => 'Informations à propos du module d\'ajout public de tickets',
  'Submit tickets without having an activeCollab account' => 'Ajouter un ticket sans posséder un compte activeCollab',
  'Module will be deactivated. Data you create using this module will not be deleted' => 'Le module sera désactivé. Les données créées utilisant ce module ne seront pas effacées.',
) ?>