<?php return array (
  'About Milestones' => 'À propos des jalons',
  'Milestones Mark Key Points in a Project' => 'Les jalons marquent les étapes clés dans un projet',
  'Milestones mark key points in a project so you can have a bird-eye view over things that needs to be done, when and who is responsible. Milestone can be a single day event or a time period with start and due date. When you need more details, you can click on a milestone\'s name to "zoom in" and see all related discussions, files and tasks' => 'Les jalons marquent les étapes clés dans un projet cela permet d\'avoir un aperçu des choses encore à réaliser, leur date de réalisation et leur responsable. Le jalon peut être une journée précise ou un intervalle de temps avec une date de départ et une date de livraison. Lorsque vous avez besoin de plus détails, vous pouvez cliquer sur le nom du jalon pour obtenir les informations relatives comme les discussions, les fichiers et les tâches ',
  'Keep Your Calendar Application in Sync with Milestones' => 'Gardez votre application de calendrier synchronisé avec vos jalons',
  'If you want to have milestones synchronized with calendars in your favorite calendar application (iCal, Outlook 2007, Google Calendar), then subscribe to iCalendar feed provided by the system. On the Calendar page you can find global feed with milestones and tasks from all active projects. The system also provides a feed for each project and you can find it by visiting overview page of the particular project' => 'Si vous voulez avoir vos jalons synchronisés avec le calendrier de votre application favorite (iCal, Outlook 2007, Google Calendar), vous pouvez vous abonner au flux iCalendar proposé par le système. Dans la page de calendrier, vous pourrez trouver un flux global avec tous les jalons et tâches depuis tous les projets actifs. Le système propose également un flux pour chaque projet. Vous pourrez trouver le lien en naviguant sur la page d\'accueil du projet en question',
  'Email Notifications' => 'Alertes e-mail',
  'Subscribe to a milestone to receive email notification when it is completed or reopened. The person responsible for the milestone can edit the list of subscribers using Manage Subscriptions tool (available from Options menu)' => 'S\'abonner à un jalon permet de recevoir des alertes e-mail lors qu\'il est terminé ou rouvert. La personne responsable du jalon peut éditer la liste des abonnés en utilisant le gestionnaire d\'abonnements (accessible depuis le menu options)',
  'Start on' => 'Débuté le',
  'Notes' => 'Remarques',
  'New Milestone' => 'Nouveau jalon',
  'Completed Milestones' => 'Jalons terminés',
  'There are no completed milestones in this project. <a href=":add_url">Create a milestone</a>.' => 'Il n\'y a aucun jalon terminé dans ce projet. <a href=":add_url">Créer un jalon</a>.',
  'Edit Milestone' => 'Modifier le jalon',
  'Milestones' => 'Jalons',
  'Milestone' => 'Jalon',
  'Active milestones' => 'Jalons actifs',
  'iCalendar' => 'iCalendar',
  'No active milestones here' => 'Il n\'y a aucun jalon actif',
  'Would you like to <a href=":add_url">create one</a>' => 'Voulez-vous en <a href=":add_url">créer un</a>',
  'Milestone <a href=":url">:name</a> has been created' => 'Le jalon <a href=":url">:name</a> a été créé',
  'Back' => 'Retour',
  'Reschedule milestone' => 'Reprogrammer le jalon',
  'With Successive Milestones' => 'Avec des jalons successifs',
  'Also reschedule all tickets and tasks that belong to milestones you are rescheduling' => 'Cela reporte également tous les tickets et les tâches qui appartiennent aux jalons que vous reportez.',
  'Reschedule' => 'Reprogrammer',
  'From / To' => 'Depuis / Pour',
  'Add to Milestone' => 'Ajouter au jalon',
  'No notes...' => 'Aucune remarque...',
  'No tasks in this milestone...' => 'Aucune tâche dans ce jalon...',
  'Milestone ":name" has been created' => 'Le jalon ":name" a été créé',
  'Milestone ":name" has been updated' => 'Le jalon ":name" a été mis à jour',
  'or' => 'ou',
  '<a href=":url">Click here</a> if you wish to reschedule this milestone' => '<a href=":url">Cliquez ici</a> si vous souhaitez reporter ce jalon',
  'You don\'t have permission for this action' => 'Vous n\'avez pas l\'autorisation pour cette action',
  'Exporting milestones data...' => 'Exportation des données des jalons...',
  'Unknown Milestone' => 'Jalon inconnu',
  'This milestone does not have any successive milestones' => 'Ce jalon n\'a aucun jalon successif',
  'Adjust all successive milestone by the same number of days' => 'Ajuster tous les jalons successifs par le même nombre de jours',
  'Adjust only selected successive milestones by the same number of days' => 'Ajuster uniquement les jalons successifs sélectionnés par le même nombre de jours',
  'Don\'t change anything' => 'Ne rien changer',
  'Add milestones to projects' => 'Ajouter des jalons aux projets',
  'Start date is not valid' => 'La date de début n\'est pas valide',
  'Due date is not valid' => 'La date de livraison n\'est pas valide',
  'Milestone name is required' => 'Le nom du jalon est obligatoire',
  'Start date is required' => 'La date de début est obligatoire',
  'Due date is required' => 'La date de livraison est obligatoire',
  'Start date needs to be before due date' => 'La date de début doit être avant la date de livraison',
) ?>